openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    training_read:
      type: object
      required:
        - uuid
        - date
        - duration
        - type
      properties:
        uuid:
          type: string
          format: uuid
        date:
          type: string
          example: 01/01/2021
        duration:
          type: number
          format: float
          example: 1.5
        type:
          type: string
          enum:
            - run
            - bike
            - walk
          example: bike
    training_cu:
      type: object
      required:
        - date
        - duration
        - type
      properties:
        date:
          type: string
          example: 01/01/2021
        duration:
          type: number
          format: float
          example: 1.5
        type:
          type: string
          enum:
            - run
            - bike
            - walk
          example: bike
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /training:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all training'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/training_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/training_cu"
      responses:
        "201":
          description: training created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/training_read"
        "401":
          description: Unauthorized
        "422":
          description: training payload is invalid
  "/training/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The training id
      responses:
        "200":
          description: training founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/training_read"
        "401":
          description: Unauthorized
        "404":
          description: training not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The training id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/training_cu"
      responses:
        "200":
          description: training modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/training_read"
        "401":
          description: Unauthorized
        "404":
          description: training not found
        "422":
          description: training payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The training id
      responses:
        "204":
          description: training deleted
        "401":
          description: Unauthorized
        "404":
          description: training not found
