openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    note_read:
      type: object
      required:
        - uuid
        - name
        - content
        - category
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: Plan to become rich
        content:
          type: string
          example: Say you can go futher than Mars
        category:
          type: string
          enum:
            - personal
            - work
            - secret
          example: secret
    note_cu:
      type: object
      required:
        - name
        - content
        - category
      properties:
        name:
          type: string
          example: Plan to become rich
        content:
          type: string
          example: Say you can go futher than Mars
        category:
          type: string
          enum:
            - personal
            - work
            - secret
          example: secret
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /note:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all note'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/note_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/note_cu"
      responses:
        "201":
          description: note created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/note_read"
        "401":
          description: Unauthorized
        "422":
          description: note payload is invalid
  "/note/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The note id
      responses:
        "200":
          description: note founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/note_read"
        "401":
          description: Unauthorized
        "404":
          description: note not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The note id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/note_cu"
      responses:
        "200":
          description: note modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/note_read"
        "401":
          description: Unauthorized
        "404":
          description: note not found
        "422":
          description: note payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The note id
      responses:
        "204":
          description: note deleted
        "401":
          description: Unauthorized
        "404":
          description: note not found
