openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    expense_read:
      type: object
      required:
        - uuid
        - name
        - date
        - amount
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: DoMac
        date:
          type: string
          example: 19/01/2021
        amount:
          type: number
          format: float
          example: 12.45
    expense_cu:
      type: object
      required:
        - name
        - date
        - amount
      properties:
        name:
          type: string
          example: DoMac
        date:
          type: string
          example: 19/01/2021
        amount:
          type: number
          format: float
          example: 12.45
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /expense:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all expense'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/expense_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/expense_cu"
      responses:
        "201":
          description: expense created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/expense_read"
        "401":
          description: Unauthorized
        "422":
          description: expense payload is invalid
  "/expense/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The expense id
      responses:
        "200":
          description: expense founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/expense_read"
        "401":
          description: Unauthorized
        "404":
          description: expense not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The expense id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/expense_cu"
      responses:
        "200":
          description: expense modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/expense_read"
        "401":
          description: Unauthorized
        "404":
          description: expense not found
        "422":
          description: expense payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The expense id
      responses:
        "204":
          description: expense deleted
        "401":
          description: Unauthorized
        "404":
          description: expense not found
