openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    talk_read:
      type: object
      required:
        - uuid
        - name
        - speaker
        - location
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: CQRS et event sourcing
        speaker:
          type: string
          example: Matthieu Moquet
        location:
          type: string
          example: Lavajug
    talk_cu:
      type: object
      required:
        - name
        - speaker
        - location
      properties:
        name:
          type: string
          example: CQRS et event sourcing
        speaker:
          type: string
          example: Matthieu Moquet
        location:
          type: string
          example: Lavajug
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /talk:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all talk'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/talk_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/talk_cu"
      responses:
        "201":
          description: talk created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/talk_read"
        "401":
          description: Unauthorized
        "422":
          description: talk payload is invalid
  "/talk/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The talk id
      responses:
        "200":
          description: talk founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/talk_read"
        "401":
          description: Unauthorized
        "404":
          description: talk not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The talk id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/talk_cu"
      responses:
        "200":
          description: talk modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/talk_read"
        "401":
          description: Unauthorized
        "404":
          description: talk not found
        "422":
          description: talk payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The talk id
      responses:
        "204":
          description: talk deleted
        "401":
          description: Unauthorized
        "404":
          description: talk not found
