openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    land_registry_read:
      type: object
      required:
        - uuid
        - commune
        - ref
        - area
      properties:
        uuid:
          type: string
          format: uuid
        commune:
          type: string
          example: Clermont-Ferrand
        ref:
          type: string
          example: D67
        area:
          type: number
          format: float
          example: 1.78
    land_registry_cu:
      type: object
      required:
        - commune
        - ref
        - area
      properties:
        commune:
          type: string
          example: Clermont-Ferrand
        ref:
          type: string
          example: D67
        area:
          type: number
          format: float
          example: 1.78
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /land_registry:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all land_registry'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/land_registry_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/land_registry_cu"
      responses:
        "201":
          description: land_registry created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/land_registry_read"
        "401":
          description: Unauthorized
        "422":
          description: land_registry payload is invalid
  "/land_registry/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The land_registry id
      responses:
        "200":
          description: land_registry founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/land_registry_read"
        "401":
          description: Unauthorized
        "404":
          description: land_registry not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The land_registry id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/land_registry_cu"
      responses:
        "200":
          description: land_registry modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/land_registry_read"
        "401":
          description: Unauthorized
        "404":
          description: land_registry not found
        "422":
          description: land_registry payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The land_registry id
      responses:
        "204":
          description: land_registry deleted
        "401":
          description: Unauthorized
        "404":
          description: land_registry not found
