openapi: 3.0.0
info:
  title: Javascript Project
  description: Api for Javascript Project
  version: 1.0.0
servers:
  - url: http://localhost:10200/api
    description: The api in the docker compose
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    wishlist_read:
      type: object
      required:
        - uuid
        - name
        - store
        - price
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
          example: Cave à vin
        store:
          type: string
          example: Boulanger
        price:
          type: number
          format: float
          example: 899.99
    wishlist_cu:
      type: object
      required:
        - name
        - store
        - price
      properties:
        name:
          type: string
          example: Cave à vin
        store:
          type: string
          example: Boulanger
        price:
          type: number
          format: float
          example: 899.99
paths:
  /login:
    post:
      tags:
        - auth
      responses:
        "200":
          description: Login success
  /wishlist:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: '"List all wishlist'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/wishlist_read"
        "401":
          description: Unauthorized
    post:
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/wishlist_cu"
      responses:
        "201":
          description: wishlist created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wishlist_read"
        "401":
          description: Unauthorized
        "422":
          description: wishlist payload is invalid
  "/wishlist/{uuid}":
    get:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The wishlist id
      responses:
        "200":
          description: wishlist founded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wishlist_read"
        "401":
          description: Unauthorized
        "404":
          description: wishlist not found
    put:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The wishlist id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/wishlist_cu"
      responses:
        "200":
          description: wishlist modified
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/wishlist_read"
        "401":
          description: Unauthorized
        "404":
          description: wishlist not found
        "422":
          description: wishlist payload is invalid
    delete:
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
            format: uuid
            example: ad1afbd2-77d2-404e-bbca-3f352f7f09a2
          required: true
          description: The wishlist id
      responses:
        "204":
          description: wishlist deleted
        "401":
          description: Unauthorized
        "404":
          description: wishlist not found
